language: go


env:
- GIMME_OS=linux    GIMME_ARCH=amd64  RUN_TESTS=1
- GIMME_OS=darwin   GIMME_ARCH=amd64
- GIMME_OS=windows  GIMME_ARCH=amd64

go:
- 1.3
- 1.4
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover

install:
- go get -d -v ./...

script:
- go build -v ./...
- if [ "$RUN_TESTS" ];
      then go test -v ./...;
      go test -coverprofile=profile.out .;
      goveralls -service=travis-ci -v -coverprofile=profile.out;
  fi